-- Store purchases are credited only by a trusted verifier using service_role.
create table if not exists public.purchase_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  platform text not null check (platform in ('android','ios')),
  transaction_id text not null,
  product_id text not null,
  gold_granted integer not null check (gold_granted > 0),
  verified_at timestamptz not null default now(),
  unique (platform,transaction_id)
);
alter table public.purchase_receipts enable row level security;
revoke all on table public.purchase_receipts from anon,authenticated;
grant select on table public.purchase_receipts to service_role;

create or replace function public.economy_grant_verified_purchase(p_user uuid,p_platform text,p_transaction text,p_product text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare amount integer; inserted bigint;
begin
  if p_platform not in ('android','ios') then raise exception 'invalid_platform'; end if;
  amount:=case p_product when 'candyblast.gold.50' then 50 when 'candyblast.gold.120' then 120 when 'candyblast.gold.300' then 300 else 0 end;
  if amount=0 then raise exception 'invalid_product'; end if;
  insert into public.purchase_receipts(user_id,platform,transaction_id,product_id,gold_granted)
  values(p_user,p_platform,p_transaction,p_product,amount)
  on conflict(platform,transaction_id) do nothing returning id into inserted;
  if inserted is null then raise exception 'purchase_already_processed'; end if;
  insert into public.player_wallets(user_id,gold_bars) values(p_user,amount)
  on conflict(user_id) do update set gold_bars=player_wallets.gold_bars+excluded.gold_bars,updated_at=now();
  return jsonb_build_object('granted',amount,'product_id',p_product);
end $$;
revoke all on function public.economy_grant_verified_purchase(uuid,text,text,text) from public,anon,authenticated;
grant execute on function public.economy_grant_verified_purchase(uuid,text,text,text) to service_role;

create or replace function public.economy_spend_gold(p_offer text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare uid uuid:=auth.uid(); cost integer; wallet public.player_wallets%rowtype;
begin
  if uid is null then raise exception 'not_authenticated'; end if;
  cost:=case p_offer when 'extra_moves' then 7 when 'hammer' then 9 when 'bomb' then 12 when 'full_lives' then 15 else 0 end;
  if cost=0 then raise exception 'invalid_offer'; end if;
  insert into public.player_wallets(user_id) values(uid) on conflict(user_id) do nothing;
  select * into wallet from public.player_wallets where user_id=uid for update;
  if wallet.gold_bars<cost then raise exception 'not_enough_gold'; end if;
  update public.player_wallets set
    gold_bars=gold_bars-cost,
    extra_moves=extra_moves+(case when p_offer='extra_moves' then 1 else 0 end),
    hammers=hammers+(case when p_offer='hammer' then 1 else 0 end),
    bombs=bombs+(case when p_offer='bomb' then 1 else 0 end),
    lives=case when p_offer='full_lives' then 5 else lives end,
    last_life_at=case when p_offer='full_lives' then null else last_life_at end,
    updated_at=now() where user_id=uid;
  return public.economy_get_state();
end $$;
revoke all on function public.economy_spend_gold(text) from public,anon;
grant execute on function public.economy_spend_gold(text) to authenticated;
